apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ruby-rails-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    # apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: ruby-rails-demo
spec:
  source:
    git:
      url: https://github.com/trevorputbrese/ruby-rails-demo
      ref:
        branch: main
