apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ruby-rails-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    # apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/trevorputbrese/rails-realworld-example-app.git
      ref:
        branch: main
