apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ruby-rails-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    # apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: ruby-rails-demo
spec:
  env:
    - name: SECRET_KEY_BASE
      value: 66347d769731732b443568c9b4528f6078c1a06a0e92106e686c35d6301fdb6f2be5bdb71a8d9dcf9dae7f1b150ebbd0b73730ae8ccbf003dcb703794d8bec2e
  source:
    git:
      url: https://github.com/trevorputbrese/ruby-rails-demo
      ref:
        branch: main
